name = "cryptoguard-api"
main = "api/index.js"
compatibility_date = "2023-12-01"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production] 
vars = { ENVIRONMENT = "production" }

# Durable Object bindings
[[durable_objects.bindings]]
name = "WEBSOCKET_MANAGER"
class_name = "WebSocketManager"

# Migration for Durable Objects (Free Plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketManager"]
